### PR TITLE
Add voting!

### PR DESCRIPTION
**Pull request by joshmfrankel**
Now we can take votes and polls quickly.

Usage notes :-)
```
#   hubot start vote item1, item2, item3, ...
#   hubot vote for N - where N is the choice number or the choice name
#   hubot show choices
#   hubot show votes - shows current votes
#   hubot end vote
```

### CODE REVIEW

**Comment by armilam** [comment]
Mind adding some instructions on how exactly voting happens?

**Comment by joshmfrankel** [comment]
@armilam I've added some instructions to the PR. Was there somewhere else that I should add them in? :-)

**Comment by armilam** [comment]
Nah, I was just curious how the interactions would happen so I can get an idea of how it works. Thanks!

**Comment by armilam** [comment]
I'm cool with this.

**Pull request merged**
